import React, { useState, useEffect, useCallback } from 'react';
import { Timeline } from './components/Timeline';
import { LevelSelector } from './components/LevelSelector';
import { CefrLevel, TenseContent, TenseId, LevelDescription } from './types';
import { generateTenseContentForLevel, generateSingleExample } from './services/geminiService';
import { FALLBACK_CONTENT, INITIAL_LEVEL_DESC, TENSES } from './constants';
import { BookOpen, Headphones, PenTool, MessageCircle } from 'lucide-react';

const App: React.FC = () => {
  const [level, setLevel] = useState<CefrLevel>(CefrLevel.A1);
  const [content, setContent] = useState<Record<TenseId, TenseContent>>(FALLBACK_CONTENT);
  const [levelDesc, setLevelDesc] = useState<LevelDescription>(INITIAL_LEVEL_DESC);
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  
  // Options State
  const [genOptions, setGenOptions] = useState({
    includeModals: false,
    includeConditionals: false
  });

  const fetchContent = useCallback(async (targetLevel: CefrLevel, options: { includeModals: boolean, includeConditionals: boolean }) => {
    setIsLoading(true);
    setError(null);
    try {
      const data = await generateTenseContentForLevel(targetLevel, options);
      setContent(data.tenses);
      setLevelDesc(data.levelDesc);
    } catch (err) {
      console.error("Failed to fetch content", err);
      setError("Unable to load AI content. Using offline mode.");
      // Keep existing content or fallback
    } finally {
      setIsLoading(false);
    }
  }, []);

  // Initial load
  useEffect(() => {
    fetchContent(CefrLevel.A1, { includeModals: false, includeConditionals: false });
  }, []); 

  const handleLevelChange = (newLevel: CefrLevel) => {
    if (newLevel === level || isLoading) return;
    setLevel(newLevel);
    fetchContent(newLevel, genOptions);
  };

  const handleOptionToggle = (key: 'includeModals' | 'includeConditionals') => {
    if (isLoading) return;
    const newOptions = { ...genOptions, [key]: !genOptions[key] };
    setGenOptions(newOptions);
    fetchContent(level, newOptions);
  };

  const handleRefreshExample = async (tenseId: TenseId) => {
    const tenseDef = TENSES.find(t => t.id === tenseId);
    const currentContent = content[tenseId];
    
    if (!tenseDef || !currentContent) return;

    try {
      const newExample = await generateSingleExample(
        level, 
        tenseDef.defaultTitle, 
        currentContent.example,
        genOptions
      );
      setContent(prev => ({
        ...prev,
        [tenseId]: {
          ...prev[tenseId],
          example: newExample
        }
      }));
    } catch (e) {
      console.error("Failed to refresh example", e);
    }
  };

  const handleShareViaGmail = () => {
    const subject = `ChronoTense Study Notes - Level ${level}`;
    
    let bodyText = `ChronoTense Study Notes\n`;
    bodyText += `Level: ${level}\n`;
    if (genOptions.includeModals) bodyText += `[Modals Included]\n`;
    if (genOptions.includeConditionals) bodyText += `[Conditionals Included]\n`;
    bodyText += `\n`;
    
    bodyText += `--- PROFICIENCY OVERVIEW ---\n`;
    bodyText += `${levelDesc.summary}\n\n`;
    bodyText += `SKILLS:\n`;
    bodyText += `* Speaking: ${levelDesc.skills.speaking}\n`;
    bodyText += `* Listening: ${levelDesc.skills.listening}\n`;
    bodyText += `* Reading: ${levelDesc.skills.reading}\n`;
    bodyText += `* Writing: ${levelDesc.skills.writing}\n\n`;
    
    bodyText += `--- TENSES ---\n\n`;
    
    TENSES.forEach(tenseDef => {
       const c = content[tenseDef.id];
       if (c) {
          bodyText += `[${c.title || tenseDef.defaultTitle}]\n`;
          bodyText += `Explanation: ${c.explanation}\n`;
          bodyText += `Example: "${c.example}"\n`;
          bodyText += `Use Case: ${c.useCase}\n\n`;
       }
    });
    
    bodyText += `Generated by ChronoTense`;
    
    const gmailUrl = `https://mail.google.com/mail/?view=cm&fs=1&su=${encodeURIComponent(subject)}&body=${encodeURIComponent(bodyText)}`;
    window.open(gmailUrl, '_blank');
  };

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 selection:bg-blue-100 selection:text-blue-900">
      <LevelSelector 
        currentLevel={level} 
        onLevelChange={handleLevelChange} 
        onShare={handleShareViaGmail}
        disabled={isLoading}
        options={genOptions}
        onToggleOption={handleOptionToggle}
      />

      <main className="pt-8">
        
        {/* Level Description Card */}
        <div className="container mx-auto px-4 mb-12">
          <div className="bg-white rounded-2xl p-6 md:p-8 shadow-sm border border-slate-100 max-w-4xl mx-auto">
            <div className="flex items-center gap-3 mb-4 border-b border-slate-100 pb-4">
              <div className="w-10 h-10 rounded-full bg-blue-600 flex items-center justify-center text-white font-bold text-lg shadow-sm">
                {level}
              </div>
              <h2 className="text-2xl font-bold text-slate-800">Proficiency Overview</h2>
            </div>
            
            <p className="text-slate-600 mb-8 leading-relaxed">
              {isLoading ? "Updating description..." : levelDesc.summary}
            </p>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <SkillCard 
                icon={<MessageCircle className="text-emerald-500" />} 
                title="Speaking" 
                text={levelDesc.skills.speaking} 
                loading={isLoading}
              />
              <SkillCard 
                icon={<Headphones className="text-blue-500" />} 
                title="Listening" 
                text={levelDesc.skills.listening} 
                loading={isLoading}
              />
              <SkillCard 
                icon={<BookOpen className="text-amber-500" />} 
                title="Reading" 
                text={levelDesc.skills.reading} 
                loading={isLoading}
              />
              <SkillCard 
                icon={<PenTool className="text-purple-500" />} 
                title="Writing" 
                text={levelDesc.skills.writing} 
                loading={isLoading}
              />
            </div>
          </div>
        </div>

        {error && (
            <div className="container mx-auto px-4 mb-8 text-center">
                <span className="inline-block px-4 py-2 bg-red-100 text-red-600 rounded-full text-sm font-medium">
                    {error}
                </span>
            </div>
        )}

        <Timeline 
          content={content} 
          isLoading={isLoading} 
          onRefreshExample={handleRefreshExample}
        />
      </main>

      <footer className="bg-slate-900 text-slate-400 py-12 mt-12 text-center text-sm">
        <p>© 2025 ChronoTense. Powered by Gemini AI.</p>
        <p className="mt-2 text-slate-600">Explore English Tenses from Beginner to Master.</p>
      </footer>
    </div>
  );
};

const SkillCard: React.FC<{ icon: React.ReactNode, title: string, text: string, loading: boolean }> = ({ icon, title, text, loading }) => (
  <div className="flex gap-4 p-4 rounded-xl bg-slate-50 border border-slate-100">
    <div className="flex-shrink-0 mt-1">
      {icon}
    </div>
    <div className="flex-1">
      <h3 className="font-semibold text-slate-900 mb-1">{title}</h3>
      {loading ? (
        <div className="h-16 bg-slate-200 animate-pulse rounded"></div>
      ) : (
        <p className="text-sm text-slate-600 leading-snug">{text}</p>
      )}
    </div>
  </div>
);

export default App;